AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Nucleus
Parameters:
  Environment:
    Type: String
    Description: The current environment where they deployment is taking place.
    Default: Development
    AllowedValues:
      - Development
      - Test
      - Production
  NotificationEmail:
    Type: String
    Description: The default e-mail address for notification purposes.
Globals:
  Function:
    Timeout: 30
    Runtime: nodejs8.10
    Handler: index.handler
    Environment:
      Variables:
        NUCLEUS_EVENT_PROCESSOR_STREAM_NAME: !Sub Nucleus-${Environment}-EventProcessor
        NUCLEUS_LOG_LEVEL: info
Resources:
  EventProcessorStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub Nucleus-${Environment}-EventProcessor
      RetentionPeriodHours: 48
      ShardCount: 1
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub Nucleus-${Environment}-UserPool
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub Nucleus-${Environment}-AppClient
      GenerateSecret: false
      UserPoolId: !Ref CognitoUserPool
  LambdaDeadLetterQueueTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub Nucleus-${Environment}-DeadLetterQueue
      Subscription:
        - Endpoint: !Ref NotificationEmail
          Protocol: email
  ProcessXAPIStatementApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      # The next section is needed because SAM does not implement API Usage Plans yet.
      # See https://github.com/awslabs/serverless-application-model/issues/248
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: !Ref AWS::StackName
          version: 1.0
        x-amazon-apigateway-request-validators:
          parameters-only:
            validateRequestParameters: true
            validateRequestBody: false
        x-amazon-apigateway-request-validator: parameters-only
        paths:
          /xAPI/statements:
            parameters:
              - in: header
                name: X-Experience-API-Version
                description: xAPI version
                required: true
                schema:
                  type: string
            post:
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProcessXAPIStatementFunction.Arn}/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
              security:
                - api_key: []
            put:
              parameters:
                - in: query
                  name: statementId
                  description: Id of Statement to record
                  required: true
                  schema:
                    type: string
                    format: uuid
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProcessXAPIStatementFunction.Arn}/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
              security:
                - api_key: []
        components:
          securitySchemes:
            api_key:
              type: apiKey
              name: x-api-key
              in: header
  CollectionApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub Nucleus-${Environment}-CollectionApiKey
      Description: Default API Key to access the Nucleus collection endpoint
      Enabled: true
  ApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - ProcessXAPIStatementApiStage
    Properties:
      ApiStages:
        - ApiId: !Ref ProcessXAPIStatementApi
          Stage: !Ref Environment
      UsagePlanName: !Sub Nucleus-${Environment}-UsagePlan
  ApiUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    DependsOn:
      - CollectionApiKey
      - ApiUsagePlan
    Properties:
      KeyId: !Ref CollectionApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiUsagePlan
  HelloNucleusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/hello-nucleus
      Handler: index.lambdaHandler
      Events:
        HelloNucleus:
          Type: Api
          Properties:
            Path: /hello
            Method: get
  ProcessXAPIStatementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/process-xapi-statement
      Events:
        PostStatements:
          Type: Api
          Properties:
            Path: /xAPI/statements
            Method: post
            RestApiId: !Ref ProcessXAPIStatementApi
        PutStatement:
          Type: Api
          Properties:
            Path: /xAPI/statements
            Method: put
            RestApiId: !Ref ProcessXAPIStatementApi
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kinesis:PutRecord
                - kinesis:PutRecords
              Resource: !GetAtt EventProcessorStream.Arn
      DeadLetterQueue:
        Type: SNS
        TargetArn: !Ref LambdaDeadLetterQueueTopic
Outputs:
  EventProcessorStreamName:
    Description: Name of the Event Processor Kinesis Data Stream
    Value: !Ref EventProcessorStream
  CognitoUserPoolId:
    Description: Generated identifier for the Cognito User Pool
    Value: !Ref CognitoUserPool
  CognitoUserPoolClientId:
    Description: Generated identifier for the Cognito User Pool App Client
    Value: !Ref CognitoUserPoolClient
  CollectionApiKeyId:
    Description: Generated identifier for the default collection endpoint API Key
    Value: !Ref CollectionApiKey
  StatementsApi:
    Description: API Gateway endpoint URL for collecting xAPI statements
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/xAPI/statements
  ProcessXAPIStatementFunction:
    Description: Process xAPI Statement Lambda function ARN
    Value: !GetAtt ProcessXAPIStatementFunction.Arn
  ProcessXAPIStatementFunctionIamRole:
    Description: Implicit IAM Role created for Process xAPI Statement function
    Value: !GetAtt ProcessXAPIStatementFunctionRole.Arn
  HelloNucleusApi:
    Description: API Gateway endpoint URL for Prod stage for Hello Nucleus function
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  HelloNucleusFunction:
    Description: Hello Nucleus Lambda Function ARN
    Value: !GetAtt HelloNucleusFunction.Arn
  HelloNucleusFunctionIamRole:
    Description: Implicit IAM Role created for Hello Nucleus function
    Value: !GetAtt HelloNucleusFunctionRole.Arn
    