AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Nucleus
Parameters:
  Environment:
    Type: String
    Description: The current environment where they deployment is taking place.
    Default: Development
  NotificationEmail:
    Type: String
    Description: The default e-mail address for notification purposes.
Globals:
  Function:
    Timeout: 30
    Runtime: nodejs8.10
    Handler: index.handler
    Environment:
      Variables:
        NUCLEUS_EVENT_PROCESSOR_STREAM_NAME: !Sub Nucleus-${Environment}-EventProcessor
        NUCLEUS_EVENT_STORAGE_STREAM_NAME: !Sub Nucleus-${Environment}-EventStorage
        NUCLEUS_EVENT_DELIVERY_STREAM_NAME: !Sub Nucleus-${Environment}-EventDelivery
        NUCLEUS_LOG_LEVEL: info
Resources:
  EventProcessorStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub Nucleus-${Environment}-EventProcessor
      RetentionPeriodHours: 48
      ShardCount: 1
  EventStorageStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub Nucleus-${Environment}-EventStorage
      RetentionPeriodHours: 48
      ShardCount: 1
  EventDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamType: KinesisStreamAsSource
      KinesisStreamSourceConfiguration:
        KinesisStreamARN: !GetAtt EventStorageStream.Arn
        RoleARN: !GetAtt EventDeliveryStreamRole.Arn
      ExtendedS3DestinationConfiguration:
        BucketARN: !GetAtt DeliveryS3Bucket.Arn
        RoleARN: !GetAtt EventDeliveryStreamRole.Arn
        BufferingHints:
          IntervalInSeconds: 300
          SizeInMBs: 5
        CompressionFormat: UNCOMPRESSED
        Prefix: "YYYY/MM/DD/HH"
  EventDeliveryStreamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "firehose.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub Nucleus-${Environment}-EventDeliveryStreamRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:*"
                Resource:
                  - !Sub arn:aws:s3:::${DeliveryS3Bucket}
                  - !Sub arn:aws:s3:::${DeliveryS3Bucket}/*
              - Effect: "Allow"
                Action:
                  - "kinesis:DescribeStream"
                  - "kinesis:GetShardIterator"
                  - "kinesis:GetRecords"
                Resource:
                  - !GetAtt EventStorageStream.Arn
  DeliveryS3Bucket:
    Type: AWS::S3::Bucket
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub Nucleus-${Environment}-UserPool
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub Nucleus-${Environment}-AppClient
      GenerateSecret: false
      UserPoolId: !Ref CognitoUserPool
  LambdaDeadLetterQueueTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub Nucleus-${Environment}-DeadLetterQueue
      Subscription:
        - Endpoint: !Ref NotificationEmail
          Protocol: email
  ProcessXAPIStatementApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      # The next section is needed because SAM does not implement API Usage Plans yet.
      # See https://github.com/awslabs/serverless-application-model/issues/248
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: !Ref AWS::StackName
          version: 1.0
        x-amazon-apigateway-request-validators:
          parameters-only:
            validateRequestParameters: true
            validateRequestBody: false
        x-amazon-apigateway-request-validator: parameters-only
        paths:
          /xAPI/statements:
            parameters:
              - in: header
                name: X-Experience-API-Version
                description: xAPI version
                required: true
                schema:
                  type: string
            post:
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProcessXAPIStatementFunction.Arn}/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
              security:
                - api_key: []
            put:
              parameters:
                - in: query
                  name: statementId
                  description: Id of Statement to record
                  required: true
                  schema:
                    type: string
                    format: uuid
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProcessXAPIStatementFunction.Arn}/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
              security:
                - api_key: []
        components:
          securitySchemes:
            api_key:
              type: apiKey
              name: x-api-key
              in: header
  ProcessXAPIBeaconApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      # The next section is needed because SAM does not implement API Usage Plans yet.
      # See https://github.com/awslabs/serverless-application-model/issues/248
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: !Sub ${AWS::StackName}-Beacon
          version: 1.0
        x-amazon-apigateway-request-validators:
          parameters-only:
            validateRequestParameters: true
            validateRequestBody: false
        x-amazon-apigateway-request-validator: parameters-only
        x-amazon-apigateway-api-key-source: AUTHORIZER
        paths:
          /xAPI/beacon:
            parameters:
              - in: query
                name: event
                description: The event payload for this request
                required: true
                schema:
                  type: string
            get:
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProcessXAPIBeaconFunction.Arn}/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                type: aws_proxy
              security:
                - beacon_authorizer: []
        components:
          securitySchemes:
            beacon_authorizer:
              type: apiKey
              name: aid
              in: query
              x-amazon-apigateway-authtype: custom
              x-amazon-apigateway-authorizer:
                type: request
                authorizerUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthorizeBeaconFunction.Arn}/invocations
                authorizerCredentials: !GetAtt AuthorizeBeaconFunctionAssumeRole.Arn
                authorizerResultTtlInSeconds: 60
                identitySource: method.request.querystring.aid
  CollectionApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub Nucleus-${Environment}-CollectionApiKey
      Description: Default API Key to access the Nucleus collection endpoint
      Enabled: true
  ApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - ProcessXAPIStatementApiStage
      - ProcessXAPIBeaconApiStage
    Properties:
      ApiStages:
        - ApiId: !Ref ProcessXAPIStatementApi
          Stage: !Ref Environment
        - ApiId: !Ref ProcessXAPIBeaconApi
          Stage: !Ref Environment
      UsagePlanName: !Sub Nucleus-${Environment}-UsagePlan
  ApiUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    DependsOn:
      - CollectionApiKey
      - ApiUsagePlan
    Properties:
      KeyId: !Ref CollectionApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiUsagePlan
  HelloNucleusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/hello-nucleus
      Handler: index.lambdaHandler
      Events:
        HelloNucleus:
          Type: Api
          Properties:
            Path: /hello
            Method: get
  AuthorizeBeaconFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/authorize-beacon
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - apigateway:GET
              Resource: !Sub arn:aws:apigateway:${AWS::Region}::/*
  AuthorizeBeaconFunctionAssumeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: "InvokeAuthorizerFunction"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - lambda:InvokeAsync
                  - lambda:InvokeFunction
                Resource: !GetAtt AuthorizeBeaconFunction.Arn
  ProcessXAPIBeaconFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/process-xapi-beacon
      Events:
        ProcessXAPIBeacon:
          Type: Api
          Properties:
            Path: /xAPI/beacon
            Method: get
            RestApiId: !Ref ProcessXAPIBeaconApi
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kinesis:PutRecord
                - kinesis:PutRecords
              Resource: !GetAtt EventProcessorStream.Arn
      DeadLetterQueue:
        Type: SNS
        TargetArn: !Ref LambdaDeadLetterQueueTopic
  ProcessXAPIStatementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/process-xapi-statement
      Events:
        PostStatements:
          Type: Api
          Properties:
            Path: /xAPI/statements
            Method: post
            RestApiId: !Ref ProcessXAPIStatementApi
        PutStatement:
          Type: Api
          Properties:
            Path: /xAPI/statements
            Method: put
            RestApiId: !Ref ProcessXAPIStatementApi
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kinesis:PutRecord
                - kinesis:PutRecords
              Resource: !GetAtt EventProcessorStream.Arn
      DeadLetterQueue:
        Type: SNS
        TargetArn: !Ref LambdaDeadLetterQueueTopic
  StoreEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/store-event
      Events:
        StoreEvent:
          Type: Kinesis
          Properties:
            Stream: !GetAtt EventProcessorStream.Arn
            StartingPosition: TRIM_HORIZON
            Enabled: true
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kinesis:DescribeStream
                - kinesis:DescribeStreamSummary
                - kinesis:GetRecords
                - kinesis:GetShardIterator
                - kinesis:ListShards
                - kinesis:ListStreams
                - kinesis:SubscribeToShard
              Resource: !GetAtt EventProcessorStream.Arn
            - Effect: Allow
              Action:
                - kinesis:PutRecord
                - kinesis:PutRecords
              Resource: !GetAtt EventStorageStream.Arn
      DeadLetterQueue:
        Type: SNS
        TargetArn: !Ref LambdaDeadLetterQueueTopic
Outputs:
  EventProcessorStreamName:
    Description: Name of the Event Processor Kinesis Data Stream
    Value: !Ref EventProcessorStream
  EventStorageStreamName:
    Description: Name of the Event Storage Kinesis Data Stream
    Value:
      Ref: EventStorageStream
  EventDeliveryStreamName:
    Description: Name of the Event Delivery Firehose Data Stream
    Value:
      Ref: EventDeliveryStream
  DeliveryS3BucketName:
    Description: Name of the S3 Bucket used by the Event Delivery Stream
    Value:
      Ref: DeliveryS3Bucket
  CognitoUserPoolId:
    Description: Generated identifier for the Cognito User Pool
    Value: !Ref CognitoUserPool
  CognitoUserPoolClientId:
    Description: Generated identifier for the Cognito User Pool App Client
    Value: !Ref CognitoUserPoolClient
  CollectionApiKeyId:
    Description: Generated identifier for the default collection endpoint API Key
    Value: !Ref CollectionApiKey
  BeaconApi:
    Description: API Gateway endpoint URL for collecting xAPI statements via a beacon
    Value: !Sub https://${ProcessXAPIBeaconApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/xAPI/beacon
  StatementsApi:
    Description: API Gateway endpoint URL for collecting xAPI statements
    Value: !Sub https://${ProcessXAPIStatementApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/xAPI/statements
  ProcessXAPIStatementFunction:
    Description: Process xAPI Statement Lambda function ARN
    Value: !GetAtt ProcessXAPIStatementFunction.Arn
  ProcessXAPIStatementFunctionIamRole:
    Description: Implicit IAM Role created for Process xAPI Statement function
    Value: !GetAtt ProcessXAPIStatementFunctionRole.Arn
  AuthorizeBeaconFunction:
    Description: Authorize Beacon Lambda function ARN
    Value: !GetAtt AuthorizeBeaconFunction.Arn
  AuthorizeBeaconFunctionIamRole:
    Description: Implicit IAM Role created for Authorize Beacon function
    Value: !GetAtt AuthorizeBeaconFunctionRole.Arn
  ProcessXAPIBeaconFunction:
    Description: Process xAPI Beacon Lambda function ARN
    Value: !GetAtt ProcessXAPIBeaconFunction.Arn
  ProcessXAPIBeaconFunctionIamRole:
    Description: Implicit IAM Role created for Process xAPI Beacon function
    Value: !GetAtt ProcessXAPIBeaconFunctionRole.Arn
  HelloNucleusApi:
    Description: API Gateway endpoint URL for Prod stage for Hello Nucleus function
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  HelloNucleusFunction:
    Description: Hello Nucleus Lambda Function ARN
    Value: !GetAtt HelloNucleusFunction.Arn
  HelloNucleusFunctionIamRole:
    Description: Implicit IAM Role created for Hello Nucleus function
    Value: !GetAtt HelloNucleusFunctionRole.Arn
  StoreEventFunction:
    Description: Store Event Lambda function ARN
    Value:
      Fn::GetAtt:
        - StoreEventFunction
        - Arn
  StoreEventFunctionIamRole:
    Description: Implicit IAM Role created for Store Event function
    Value:
      Fn::GetAtt:
        - StoreEventFunctionRole
        - Arn
